0.0.0 script to transition an existing installation into the new way
timescale/promscale_extension pull request #133
Opened 2022-03-17 02:14 UTC by jgpruitt

2022-03-17 19:12 UTC, cevian requested changes
A few issues. Biggest one is why are the object ownership changed to extowner and not superuser?

2022-03-17 19:12 UTC, cevian commented on sql/promscale--0.0.0.sql
> +        EXECUTE format('ALTER %s %s OWNER TO %I', _rec.objtype, _rec.objname, '@extowner@');
shouldn't this be to superuser not extowner? I also wonder why this wasn't caught by the tests.

2022-03-17 19:12 UTC, cevian commented on sql/promscale--0.0.0.sql
> +        EXECUTE format($sql$ALTER %s %I.%I OWNER TO prom_modifier$sql$, _rec.typ, _rec.nspname, _rec.relname);
this will need to change to the superuser as in the other PR.

2022-03-17 19:12 UTC, cevian commented on sql/promscale--0.0.0.sql
> +
don't we need to drop the old schema migration table here?

2022-03-18 13:51 UTC, cevian approved these changes

2022-03-18 14:00 UTC, sumerman approved these changes

2022-03-18 14:00 UTC, merged