SHA512 based JSONB digest funciton
timescale/promscale_extension pull request #149
Opened 2022-03-21 14:21 UTC by sumerman

2022-03-22 12:07 UTC, JamesGuthrie requested changes

2022-03-22 12:09 UTC, JamesGuthrie commented on src/raw.rs
> +raw_type!(Jsonb, pg_sys::JSONBOID, pg_sys::JSONBARRAYOID);
In case it wasn't clear: I don't think that we should change anything in how we've implemented this.

2022-03-22 12:22 UTC, sumerman commented on src/jsonb_digest.rs
> +    let jsonb = pg_detoast_datum(jsonb_datum.0 as *mut varlena) as *mut Jsonb;
Yes and no. Everything within a memory context will be freed at once. Usually at the end of the query in this case. In the upcoming commit I've separated json iterator into its own thing and handling this explicitly.

2022-03-22 12:23 UTC, sumerman commented on src/jsonb_digest.rs
> +    if jsonb_datum.0 == 0 {
Good to know! Thanks!

2022-03-22 12:25 UTC, sumerman commented on src/jsonb_digest.rs
> +    Vec::from(hasher.finalize().as_slice())
Good point. But we if chase this, I'll be cutting it too close to GA. @cevian WDYT?

2022-03-22 12:27 UTC, sumerman commented on src/raw.rs
> +raw_type!(Jsonb, pg_sys::JSONBOID, pg_sys::JSONBARRAYOID);
`pgx::JsonB` converts the whole thing into a string and then parses it. Not what I wanted. Built my own type already.

2022-03-22 12:28 UTC, sumerman commented on src/jsonb_digest.rs
> +                        0x04u8.to_le_bytes()
Parroting from `jsonb_hash_extended`, doesn't really matter AFAICT, just needs to be distinct from everything else.

2022-03-22 12:29 UTC, sumerman commented on src/jsonb_digest.rs
> +pub unsafe fn jsonb_digest(jsonb_datum: crate::raw::Jsonb) -> Vec<u8> {
As I've mentioned elsewhere, I've separated JSON traversal into an abstraction of its own. All unsafe bits will be hidden behind.

2022-03-22 12:32 UTC, sumerman commented on src/jsonb_digest.rs
> +    use sha2::{Digest, Sha512};
No particular reason. Changed that already.

2022-03-22 12:32 UTC, sumerman commented on src/jsonb_digest.rs
> +                jbvType_jbvNull => hasher.update(0x01u8.to_le_bytes()),
Parroting from jsonb_hash_extended, doesn't really matter AFAICT, just needs to be distinct from everything else.

2022-03-23 09:14 UTC, sumerman commented
Fun fact, `json_digest` is ever so slightly faster than `sha512(json::text::bytea)`

```
SELECT sha512(gen.json::text::bytea)
FROM (
	SELECT jsonb_object_agg(n::text, n) AS json
	FROM generate_series(1, 2000000) AS gs (n)
) AS gen;

 Planning Time: 0.065 ms
 Execution Time: 2306.121 ms

SELECT jsonb_digest(gen.json)
FROM (
	SELECT jsonb_object_agg(n::text, n) AS json
	FROM generate_series(1, 2000000) AS gs (n)
) AS gen;

 Planning Time: 0.062 ms
 Execution Time: 2195.345 ms
```

2022-03-23 15:10 UTC, sumerman commented on src/jsonb_digest.rs
> +    Vec::from(hasher.finalize().as_slice())
As discussed elsewhere `sha512` is actually 64 bytes long and `varlena` header end's up being a much smaller fraction 😅

2022-03-23 17:20 UTC, JamesGuthrie commented on src/iterable_jsonb.rs
> +    fn extract_string_value(jsonb_val: &mut JsonbValue) -> &'a str {
nit: Here's a potential candidate for `unsafe fn`. It's only safe to call this when the caller has validated the `JsonbValue`'s type is 'jbvString'.

2022-03-23 17:34 UTC, sumerman commented on src/jsonb_digest.rs
> +            //
No, I just wanted a visual separation between "scalars", "objects" and "arrays". Perhaps I should name them.

2022-03-23 18:54 UTC, merged

2022-03-29 15:20 UTC, jgpruitt reviewed
LGTM