Document general structure of `migration` directory
timescale/promscale_extension pull request #201
Opened 2022-04-26 12:27 UTC by JamesGuthrie

2022-04-26 13:51 UTC, jgpruitt requested changes
One minor nit.

2022-04-28 08:01 UTC, JamesGuthrie commented on migration/README.md
> +When adding new SQL, you need only the `incremental` and `idempotent` components
Oh man. I wrote this while waiting at the city administration office in a room with 30 other people - 🤦

2022-04-28 08:12 UTC, sumerman approved these changes

2022-04-28 20:11 UTC, cevian approved these changes

2022-04-28 20:13 UTC, jgpruitt approved these changes

2022-04-29 06:15 UTC, merged