Tracing tables internals documentation
timescale/promscale_extension pull request #397
Opened 2022-07-05 18:24 UTC by sumerman

## Description

The missing piece to resolve #159 -- a document that goes over relationships between tables from `_ps_trace` schema.

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [x] Updated the relevant documentation

2022-07-05 21:39 UTC, jgpruitt commented on docs/sql-tracing-tables.md
> +operators have [`tag_map_rewrite` support funciton](../src/support.rs) attached
nit: "function" is misspelled.

2022-07-05 21:40 UTC, jgpruitt commented on docs/sql-tracing-tables.md
> +- similarily `operation_id` references `opertaion` table.
nit: "operation" is misspelled

2022-07-06 07:16 UTC, JamesGuthrie requested changes

2022-07-06 07:32 UTC, JamesGuthrie approved these changes

2022-07-06 13:35 UTC, merged