Update SQL objects in accordance with new downsampling UX
timescale/promscale_extension pull request #596
Opened 2022-12-20 15:31 UTC by Harkishen-Singh

Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>

TODO
1. Write about new downsampling UX
2. Write about enable and disable feature for automatic-downsampling
3. Write about separate delete function for automatic-downsampling

## Description

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

2022-12-21 20:03 UTC, jgpruitt requested changes

2022-12-23 11:03 UTC, Harkishen-Singh commented on sql-tests/testdata/metric_downsampling.sql
> +\set ON_ERROR_STOP 1
I am not sure if pgtap is helpful for this test. The test mostly confirms the table structure of `dowmsample`, `metric_downsample` and related metrics, so it was easier to use snapshots.

2023-01-02 11:44 UTC, Harkishen-Singh commented
Note: I have added another commit `Add querying view & support for dowmsampling metrics with no metadata` that is not primarily related to this PR. I wanted to avoid conflicts between creating another PR (from feature_metric_rollup branch) and this PR getting merged, hence reused this PR itself.

2023-01-02 11:45 UTC, Harkishen-Singh commented on migration/idempotent/017-metric-downsampling.sql
> +-- This creates a view that acts as a interface between connector and the downsampled data while querying.
This is the new part added in second commit.

2023-01-02 11:45 UTC, Harkishen-Singh commented on migration/idempotent/017-metric-downsampling.sql
> +        -- Guess the metric type based on the metric/table suffix.
This too as part of second commit.

2023-01-03 13:56 UTC, Harkishen-Singh commented on migration/idempotent/017-metric-downsampling.sql
> +    query TEXT := 'CREATE OR REPLACE VIEW %1$I.q_%2$I AS SELECT time, series_id, %3$s AS value FROM %1$I.%2$I';
See commit [Adds support to query default downsampling views in absence of `__column__`](https://github.com/timescale/promscale/pull/1808/commits/7464174d04281b2e81652fa8c1c6c08b13378075) for understanding the use of this view.

2023-01-05 11:03 UTC, niksajakovljevic commented
It would be great to rename `resolution` to `interval` so it's in line with connector naming.

2023-01-10 09:48 UTC, merged